### ISSUE TITLE
custom header using Amplify and AppSync w/ IAM Authentication

### ISSUE THREAD

**Issue by honkskillet** [awslabs/aws-mobile-appsync-sdk-js#119]
I have an AppSync project using IAM AuthN.  I use Amplify on the client to get user data from a cognito user pool.  I would like to be able to add a custom head to my graphQL requests that I can use in my AppSync Lambda datasources for Authorization (AuthR).  I have tried different configs with Amplify, such as ...

```
export default {
    "graphqlEndpoint": "https://bomgobomgobomgo.appsync-api.us-west-2.amazonaws.com/graphql",
    "graphqlHeaders": async () => ({
        'My-Custom-Header': 'my value'
    }),
    "region": "us-west-2",
    "authenticationType": "AWS_IAM",
    "apiKey": null, 
}
```

I have also tried adding an Apollo link

```
const authRLink = new ApolloLink((operation, forward) => {
  operation.setContext({
    headers: {
      'My-Custom-Header': 'my value'
    }
  })
  return forward(operation)
})
````

Also tried httpLink and many different variations of the above but it seems that either I haven't found the right combo or that AppSync overwrite the header.  Is there a way to send custom headers back to the server side.

**Comment by ajmath** [comment]
I think this is because of a bug in the auth link.  If you look at the code (here)[https://github.com/awslabs/aws-mobile-appsync-sdk-js/blob/master/packages/aws-appsync/src/link/auth-link.js#L93], you can see that they are not including the original headers when adding the auth headers.  This is a problem for all auth types.
