### ISSUE TITLE
Ionic 4 and Angular supporting documentation and examples

### ISSUE THREAD

**Issue by selipso** [awslabs/aws-mobile-appsync-sdk-js#262]
Want to create an issue to track usage and code samples with Ionic framework until the documentation catches up. Hopefully this can eventually act as a foundation for a significant PR for adding more documentation. So far, I've found this resource with sample code in one of the comments in another issue:

https://github.com/aws-samples/aws-mobile-appsync-chat-starter-angular

Some of the code in that repo may be outdated because of recent version updates but I'm hoping to comb through it and start documenting valid API endpoints. Hopefully soon we can have examples on how to achieve offline sync support with Angular, which feels left out of the current React and Vue samples.

**Comment by elorzafe** [comment]
Hi @selipso thanks for your feedback. We are working on update this.

**Comment by dimitarrusev** [comment]
@elorzafe Can you provide an ETA on this? Because i've been hearing the same thing since the beginning of the year.

**Comment by undefobj** [comment]
@selipso @dimitarrusev that repo is actually a sample maintained separately from the SDK team. Is there something specific in the AppSync SDK that you're looking to be documented for Angular 4 or Ionic? Otherwise if it's updating some of the code in that sample repo it would be best to open an issue there.

**Comment by undefobj** [comment]
@dimitarrusev so in the README a usage guide for Angular is something we can do, however we need to do a little more work in our Amplify codegen to make the Angular/Ionic services easier to setup. This is good feedback we can work on. Most likely we'll have similar instructions for the Amplify GraphQL client too in this section: https://aws-amplify.github.io/amplify-js/media/ionic_guide

**Comment by dimitarrusev** [comment]
@undefobj That’s good to hear, but i was hoping to get an ETA. Because like i said earlier, support for Angular has been in this “coming soon” state since March, and currently it’s October. 

So “coming soon” is not helpful anymore, especially when the only option we are left with is to use Amplify’s GraphQL client which is not good enough to build anything meaningful (no support for caching, refetch queries, optimistic UI etc).

**Comment by undefobj** [comment]
@dimitarrusev I'm not sure which update in March you are referring to that said there would an Angular guide or specific code. Could you point me to an issue or post that said that? Regardless, you can use this library with Ionic and Angular today as some people have done in the starter application referenced earlier. We want to provide a great developer experience for all frameworks and manually building up the services by hand and documenting that would be quite verbose hence why we're looking to automate it for you. I cannot provide ETAs on delivery but I can say that we're looking at this in the coming month and if it ends up being straight forward you should see something after that.

@selipso yes this is what we're looking to automate better for Angular and Ionic customers such as yourself. We have the [offline helpers](https://github.com/awslabs/aws-mobile-appsync-sdk-js/blob/master/OFFLINE_HELPERS.md) that can do much of this in any JavaScript library which you can use in conjunction with [@versioned in the GraphQL Transformer](https://github.com/aws-amplify/amplify-cli/blob/master/graphql-transform-tutorial.md) of the [Amplify CLI](https://github.com/aws-amplify/amplify-cli) when setting up your backend, but our goal is to make all aspects of your framework experience first class just like the others.

cc @mlabieniec

**Comment by selipso** [comment]
Found another resource that can be helpful: https://docs.aws.amazon.com/appsync/latest/devguide/building-a-client-app-node.html

Specifically, this code sample that sets up the client for node.js may have an equivalent snippet in Ionic / Angular.

```js
// Set up Apollo client
const client = new AWSAppSyncClient({
    url: url,
    region: region,
    auth: {
        type: type,
        credentials: credentials,
    }
});

client.hydrated().then(function (client) {
    //Now run a query
    client.query({ query: query })
        .then(function logData(data) {
            console.log('results of query: ', data);
        })
        .catch(console.error);

    //Now subscribe to results
    const observable = client.subscribe({ query: subquery });

    const realtimeResults = function realtimeResults(data) {
        console.log('realtime data: ', data);
    };

    observable.subscribe({
        next: realtimeResults,
        complete: console.log,
        error: console.log,
    });
});
```
In the above case, it looks like the AWSAppSyncClient is being used as a wrapper around `apollo-client`.

However, `apollo-angular` provides a service that acts as an `@Injectable()`. Maybe the following could be a worksround in Ionic / Angular applications to provide a similar Service as `apollo-angular` for AppSync? Haven't gotten the chance to test the following code yet, but here goes:

```ts
import { AWSAppSyncClient } from 'aws-appsync';

@Injectable({
    providedIn: 'root',
    useValue: new AWSAppSyncClient({
        url: url,
        region: region,
        auth: {
            type: type,
            credentials: credentials,
        }
    });
})
export class BackendService { }
```

**Comment by dimitarrusev** [comment]
@undefobj BTW, sorry about not responding to your reply. I must have missed that. I was referring to your README (check out the commit history). But, now that i have this figured out, i am willing to contribute to the docs. Should we discuss this beforehand or should i just go ahead and submit my contribution?

**Comment by selipso** [comment]
@dimitarrusev Thanks for the tip, will report back here once I have the chance to test out both methods. Currently working on the server-side for a bit with the Serverless framework and AppSync. You guys are really pushing out seamless integration tools and updates with GraphQL and the node.js ecosystem in general. Keep it up! I was an inactive AWS user for like 4 years (lol) until now I'm switching away from deploying to my own containers / servers / dynos, etc.

**Comment by undefobj** [comment]
Hi @dimitarrusev @selipso thanks for the comments. We've actually just completed yesterday our "phase 1" of the Angular & Ionic support by releasing an update to the codegen feature of the Amplify CLI. It currently works for the Amplify GraphQL client and our "phase 2" will be doing this with the Apollo client as well. You can see the documentation for this here: https://aws-amplify.github.io/docs/js/api#angular

You'll notice that we create an Angular service for you to use directly in your app. The client interfaces are different for the Amplify GraphQL client vs the Apollo client which is why we split this work into stages. If you want to email me (richthr_AT_amazon - replace _AT_ with @) with your thoughts on what your requirements for doing codegen in a similar manner with Apollo client that would be great. I could also get you involved in a couple early beta test builds.

cc @mlabieniec

**Comment by selipso** [comment]
@undefobj Gave the docs a first glance and they look great. Will let you know if I have any questions / suggestions as I start going through their implementation. Thanks for the resource. I'll close this as being well addressed now.

**Comment by pickfire** [comment]
Any news on this, I tried to do this but have yet find any good links to solve it.

**Comment by dodomui** [comment]
Me too, keen to start appsync with Ionic, any suggestion?
Spend few weeks, didn't manage to make it with appsync yet.
