### ISSUE TITLE
$util.autoId() hex value

### ISSUE THREAD

**Issue by sterlingshrey** [awslabs/aws-mobile-appsync-sdk-js#284]
Not sure, if this is the right place for feature request.

Apparently, $util.autoId() returns UUID string in format: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx. I couldn't find a way to get it in hex format without hyphens. I don't think, it's a good idea to unnecessarily waste 4 bytes for every entry in dynamodb table.

**Comment by undefobj** [comment]
It wouldn't be a UUID then if you remove those values: https://en.wikipedia.org/wiki/Universally_unique_identifier

The reason AppSync does this is to automatically help you distribute your data efficiently over DynamoDB partitions. Removing those just for a few bytes might end up causing negative impact for throughput distribution. Also you might not actually see any savings in aggregate.

**Comment by sterlingshrey** [comment]
Sorry! 

Can you elaborate the part where you said:
"... might end up causing negative impact for throughput distribution"

Just wanted to understand, how a random hash-key(with reasonable hash-function) with or without dashes negatively affect distribution of data?

**Comment by pronevich** [comment]
@sterlingshrey @undefobj I can't say how UUID provided by AppSync `$util.autoId()` will help with data efficiency, because when we talk about DynamoDB many factors appear about your query patterns, primary and sort key modeling and etc. For me provided UUID is a problem, I need smaller and url friendly ids. Also when modeling hierarchical relations where we store all parents in the field - UUID's are too long for this. The solution will provide a more agile and useful id generator https://github.com/ai/nanoid
