### ISSUE TITLE
Mutation occurring twice despite being called only once when optimisticResponse is not specified

### ISSUE THREAD

**Issue by rivertam** [awslabs/aws-mobile-appsync-sdk-js#30]
I have a fairly simple React object, and I'm trying to pass it as parameters to a GraphQL mutation (apologies if my terminology is flawed; I'm new to GraphQL).

The following is how I'm using the `compose` and `graphql` HOCs on my component `CompanyList`. In my code, I'm calling the prop `createUser` one time.

```javascript
export default compose(
  graphql(MutationCreateCompany, {
    // ...
  }),
  graphql(QueryAllCompanies, {
    // ...
  }),
  graphql(MutationCreateUser, {
    props: props => ({
      createUser: user => {
        console.log('mockingbird');
        return props.mutate({
          variables: user,
          /*optimisticResponse: () => ({
            createUser: { ...user, __typename: 'User' },
          }),*/
        });
      },
    }),
  }),
)(CompanyList);
```

```javascript
import gql from 'graphql-tag';

export const MutationCreateUser = gql`
  mutation PutUserMutation(
    $username: String
    $email: String!
    $name: String
    $title: String
  ) {
    putUser(username: $username, email: $email, name: $name, title: $title) {
      username
      email
    }
  }
`;
```

**Intended outcome:**

Only one POST request would be made with my mutation.

**Actual outcome:**

Two POST requests are being made with identical mutations at the same time.

The word "mockingbird" is printed only once.

Only one POST request is made if I provide an `optimisticResponse` option (if I uncomment it from above)

**Comment by nicokruger** [comment]
This is happening to me as well, using vue-apollo. 

By adding an optimisticResponse I got rid of the double POSTs.

However, that seemed to add another set of worms - as the optimisticResponse is never replaced with the real data, and vue-apollo's update() method gets called twice both times with the optimisticResponse, instead of the optimistcResponse and then the real response.

Would be interested to hear if you see the same behaviour, as its difficult to know if it is appsync or vue-apollo causing my second issue.

**Comment by ajagnanan** [comment]
this is happening for me too 😢
