### ISSUE TITLE
Question: How do I use the Amplify CLI to generate Appsync API that uses Delta Sync?

### ISSUE THREAD

**Issue by pmbanugo** [awslabs/aws-mobile-appsync-sdk-js#318]
Hi.

I've read the docs on DeltaSync. However, the implementation is something I don't know how to proceed. I've read this [doc](https://docs.aws.amazon.com/appsync/latest/devguide/tutorial-delta-sync.html) which provides a cloudformation stack to implement a sample Appsync API that supports Delta Sync query, but I assume it a problem for me. I already have a stack generated and run by the Amplify CLI. I've thought about adding those columns manually to my table and trying to follow the docs to create queries and DynamoDb with TTL and maybe resolvers to make this work. But that would be a long manual process which might not work. 

How do I use Amplify CLI to generate API that allows for Delta SYnc queries?

**Comment by undefobj** [comment]
Hi @pmbanugo this would be a better question logged in the Amplify CLI repo. It's not supported at this time which is why the CloudFormation stack is provided as a sample, however the CLI team can take your question as a feature request and prioritize it with other members of the community. For convenience I've created an issue in that repo for you referencing this and will close this now.
