### ISSUE TITLE
Question: Cognito & Amplify required for S3 Complex Object Appsync Feature

### ISSUE THREAD

**Issue by bowlwinkle** [awslabs/aws-mobile-appsync-sdk-js#326]
>  Note: If your issue/feature-request/question is regarding the AWS AppSync service, please log it in the 
  [official AWS AppSync forum](https://forums.aws.amazon.com/forum.jspa?forumID=280&start=0)

**Do you want to request a *feature* or report a *bug*?**
No

**What is the current behavior?**
I am not using amplify
I am trying to upload image resources to a bucket using appsync (following the [example repo](https://github.com/aws-samples/aws-amplify-graphql))
Everything works if I drop `localUri` from the mutation but as soon as I fill localUri with `type File` the request isn't sent.
![image](https://user-images.githubusercontent.com/2514697/50252436-d29f9a00-039b-11e9-9744-0a882ee7badf.png)

When I say everything works, I mean, the mutation is sent and stored in Dynamo but if I give the mutation the File in localUri, zero requests are sent from the browser. Seems like a client side check.

I define the inputs directly: S3Object and S3ObjectInput nested in my Post { name, image: S3Object, ... }

I do not provide complexObjectsCredentials as I do not use aws cognito
I would like to configure using OPENID_CONNECT

**Question:** Does AppSync support complex object upload without Cognito creds and without configuring with amplify?  If so, do you have any suggestions as to what I may be doing wrong.
It seems the client determines something is wrong and doesn't send anything if I give the mutation localUri.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
I don't think it is a bug, more of support...

**What is the expected behavior?**
Allow S3 Complex Object Appsync Feature without using Amplify

**Which versions and which environment (browser, react-native, nodejs) / OS are affected by this issue? Did this work in previous versions?**

Chrome: Version 70.0.3538.110 (Official Build) (64-bit)
React: 16.0.0
aws-appsync: "^1.4.0",
aws-appsync-react: "^1.2.0",
Node: 8.11.3

Did this work in a previous version: no/haven't tried previous versions

**Comment by elorzafe** [comment]
Hi @bowlwinkle, In order to upload files securely to Amazon S3 you need AWS credentials. This credentials are used to sign the request (Amazon S3 validates this credentials in order for the upload to succeed). Amazon S3 currently doesn't support JWT as authentication type.

AppSync client needs these credentials in order to upload the files to Amazon S3. You need to provide complexObjectCredentials to make this work.

A recommended way to get AWS credentials on your client apps is to use Amazon Cognito Federated Identities (Identity Pool), you can create this using Cognito console or [amplify-cli](https://github.com/aws-amplify/amplify-cli). You can add an auth provider on your identity pool to enable auth access to your resources.  In my opinion the easiest way to do this is using amplify-cli

I hope this can help you.

**Comment by bowlwinkle** [comment]
ack; you can close

Thanks

**Comment by mikechambers610** [comment]
Is there any difference with sending a file via complex object in react-native as opposed to through a browser?

**Comment by mikechambers610** [comment]
@elorzafe

**Comment by mikechambers610** [comment]
Thanks @elorzafe I have created https://github.com/awslabs/aws-mobile-appsync-sdk-js/issues/335

I am not sure what is missing from my project but have had no luck with getting my S3Object working through Appsync from React-Native.
