### ISSUE TITLE
Merging mutations when offline

### ISSUE THREAD

**Issue by StefanFabian** [awslabs/aws-mobile-appsync-sdk-js#328]
I've noticed that when mutating while offline and then going online all mutations will be sent in sequence.
So far so good, that's intended I know but in my case some of these mutations are mutating the same object so it would make sense to merge them before they are sent to avoid the overhead of sending 3 requests for what could be done in a single request.

Is there any way to do this?
Perhaps some way of checking if there is a pending mutation and if the ids match just updating the variables of that mutation with the new values.

**Comment by elorzafe** [comment]
@StefanFabian thanks for your comments.

Currently is not possible to merge this changes.

I am to happy to talk with you about this, but I think the problem is more complex. I agree that in some cases like you mention, updating the same object seems reasonable to merge into one, the tricky part is to keep consistency on the cache (mutations also have update function that can change other part of the cache), and also if other objects depend of it (for example comments on events that have server generated ids, AppSync client has an idsMap to keep consistency for when the server response arrives with the new id). In which position of the queue it should be merge (first mutation/last mutation)

Maybe this could be configurable on the client? Telling AppSync client which mutations should be merged into one? So the developer will know the behavior of the app?

What do you think?

**Comment by StefanFabian** [comment]
I was thinking of a purely client side back online callback maybe where you can access the mutations that are going to be sent to the server and modify this list.
However, I agree that there are quite some possible complications with the state if it isn't properly taken care off and the original mutations update methods shouldn't run because they might conflict or maybe the original mutation doesn't even exist anymore.

The more I think about it, the more I think that it's not really worth the hassle.

**Comment by elorzafe** [comment]
@StefanFabian Do you think I should close this issue for now? We can discuss in the future other improvements for offline support.

**Comment by StefanFabian** [comment]
Yeah, I think there's no reason to keep it open for now.
