### ISSUE TITLE
Missing field id in createPost mutation

### ISSUE THREAD

**Issue by yhenni1989** [awslabs/aws-mobile-appsync-sdk-js#380]
>  Note: If your issue/feature-request/question is regarding the AWS AppSync service, please log it in the 
  [official AWS AppSync forum](https://forums.aws.amazon.com/forum.jspa?forumID=280&start=0)

**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
Calling the createPost mutation throws the following error

![Error](https://user-images.githubusercontent.com/26605247/54869425-08d02980-4d90-11e9-89f3-def83ac70a07.png)

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

Create post Mutation

<img width="334" alt="mutation" src="https://user-images.githubusercontent.com/26605247/54869430-17b6dc00-4d90-11e9-88e4-094eaaf84509.png">

Query list of posts

<img width="334" alt="query" src="https://user-images.githubusercontent.com/26605247/54869433-200f1700-4d90-11e9-81ae-69aaa1dee5be.png">

Decorator 

<img width="541" alt="Apollo" src="https://user-images.githubusercontent.com/26605247/54869464-83994480-4d90-11e9-9285-b9b8aefbb0e2.png">

**What is the expected behavior?**
The logic runs fine when adding the id field into the mutation.

<img width="373" alt="Correct" src="https://user-images.githubusercontent.com/26605247/54869480-b6dbd380-4d90-11e9-896a-934cb32cc0f5.png">

**Which versions and which environment (browser, react-native, nodejs) / OS are affected by this issue? Did this work in previous versions?**
React Native

**Comment by NeillGiraldo** [comment]
This is an expected behavior. 
The issue here is that, during your mutation, you are providing a different 'structure' of the object that is defined on your query. 
In your [query](https://user-images.githubusercontent.com/26605247/54869433-200f1700-4d90-11e9-81ae-69aaa1dee5be.png) you expect objects to have this structure.
`{
id
name
}`
however, what is being returned from your [mutation](https://user-images.githubusercontent.com/26605247/54869430-17b6dc00-4d90-11e9-88e4-094eaaf84509.png) and being written into the store is an object with this structure.
`
{
name
}
`
I am not sure if during the OptimisticResponse, your post object has the correct structure, but certainly when the second call of the update function is triggered with the server's response, The Apollo client writes into the store an object with an invalid structure. 
So when you query the store after writing a single object, an error in types will rise, as the query is expecting all the objects to have an id attribute.

**Comment by haverchuck** [comment]
@jtaylor1989 - Does the response from @NeillGiraldo make sense?

**Comment by jtaylor1989** [comment]
Yes it does.
