### ISSUE TITLE
Apollo-client dependency version

### ISSUE THREAD

**Issue by miiihi** [awslabs/aws-mobile-appsync-sdk-js#436]
Latest aws-appsync is using apollo-client@2.4.6, which is more than 9 months old and has at least one serious bug (solved already, see https://github.com/apollographql/apollo-client/pull/4352).
Are there any obstacles to update to latest versions of dependant libraries? And plans about that?

Thanks, miiihi

**Comment by jimmyn** [comment]
Please upgrade  apollo-client, it is very much needed for hooks support

**Comment by jimmyn** [comment]
Any updates here? this is very much needed.

**Comment by beezeebly** [comment]
Hi @jimmyn, I followed the comment [here](https://github.com/apollographql/react-apollo/issues/3148#issuecomment-511622210) to update the Apollo Client to 2.6.3 in order to use "@apollo/react-hooks:0.1.0-beta.11". 

If you're using Yarn, force AppSync to resolve to Apollo Client 2.6.3 by adding the following to your package.json:

```
"resolutions": {
    "apollo-client": "2.6.3"
  }
```

**Comment by ryanwalters** [comment]
`@apollo/react-hooks` is out of beta, hopefully this gets a little more attention from the AppSync team now. 

> "React Apollo 3 uses hooks behind the scenes for everything, including the  graphql HOC and render prop components." — [Apollo Docs](https://www.apollographql.com/docs/react/hooks-migration/#bundle-size-note)

**Comment by tjhowe** [comment]
@beezeebly Have you had any issues with the fixing the apollo client?

Also hopeful that the apollo client can be bumped. Mainly for a resolution to the bug @miiihi 's pointed out, but also the new @apollo/react-hooks lib.

**Comment by nathanbirrell** [comment]
This really needs attention

**Comment by undefobj** [comment]
Hello everyone - I want to reply and assure you that we have not abandoned support of this project. Per my earlier comment, this is a complex process and to be completely transparent there are things in the Apollo library that are out of our control and there have also been breaking changes in Apollo versions which we're trying to account for, which is also why we pinned the version. We've been spending many hours trying to account for this but it's not simple to solve. After putting more thought into this we've got some initial solutions that I hope will unblock many of you. What we've done is packaged two of the "Links" which are part of the SDK - the Auth and Subscription Links - and published them to NPM. This will allow you to include them in the newer Apollo versions if you wish to use the newer features. This does not include the "Offline Link" for offline support which is more complex to solve and we're looking into for the future.

Installation of the links:

```
npm install aws-appsync-auth-link aws-apsync-subscription-link
```

Usage:
https://github.com/awslabs/aws-mobile-appsync-sdk-js#using-authorization-and-subscription-links-with-apollo-client-no-offline-support
 
With is I would then give the following recommendations for choosing your client strategy:

1. If you do **not** have offline use cases, you can either use the Auth & Subscription Links above with the latest Apollo client or alternatively use the Amplify GraphQL client instead of Apollo:https://aws-amplify.github.io/docs/js/api#amplify-graphql-client  
2. If you **do have offline use** cases please use the current version as-is with the older Apollo version. We're still working on a future strategy for the Offline Link.

Please let us know if you have any trouble using these links or if there is a scenario which we haven't accounted for here.

**Comment by pickfire** [comment]
`apollo-link-http` also needs to be updated, codegen depends on the newer versions.

**Comment by royalaid** [comment]
I don't want to pile on to the issue that will already be a ton of work but merely want to point out that Apollo 3.0 is [coming](https://github.com/apollographql/apollo-client/blob/release-3.0/CHANGELOG.md#breaking-changes)

**Comment by BenoitDel** [comment]
Is there any roadmap for apollo-client 3.0 support ?

**Comment by ianmartorell** [comment]
I was looking to use Amplify and AppSync with `@apollo/react-hooks` and realized it's not working. It's been almost a year since your last comment @undefobj, are there any updates you can share? Thanks!

**Comment by hutber** [comment]
Ye, it very much seems this project has been abandoned now sadly. @ianmartorell I think the only solution for us (me) to write my own client which shouldn't be too hard in theory I believe.

Still a shame though

**Comment by manueliglesias** [comment]
Hi,

If you have a need for just Apollo 3 support without offline, we just published updated versions of the links

See: https://github.com/awslabs/aws-mobile-appsync-sdk-js/pull/561#issuecomment-701696316


If you need offline support, we recommend you use [Amplify DataStore](https://docs.amplify.aws/lib/datastore/getting-started/q/platform/js)

**Comment by treyspiva** [comment]
> If you need offline support, we recommend you use Amplify DataStore

Does this mean you have given up implementing offline support?  The DataStore is not good if you want to use a query and get relationships.  You have to make multiple queries.  It is more like using an ORM in your frontend code.  Which defeats a big part of the benefit of using GraphQL.  This is more like going back to a REST API.
