### ISSUE TITLE
Warning: Failed context type: Invalid context `client` of type `AWSAppSyncClient` supplied to `Rehydrated`, expected instance of `AWSAppSyncClient`

### ISSUE THREAD

**Issue by sid88in** [awslabs/aws-mobile-appsync-sdk-js#50]
with new upgrade in packages I get warning

```
index.js:2178 Warning: Failed context type: Invalid context `client` of type `AWSAppSyncClient` supplied to `Rehydrated`, expected instance of `AWSAppSyncClient`.
    in Rehydrated (at App.js:36)
    in QueryRecyclerProvider (created by ApolloProvider)
    in ApolloProvider (at App.js:35)
    in Router (created by BrowserRouter)
    in BrowserRouter (at App.js:34)
    in WithProvider (created by _class)
    in div (created by _class)
    in _class (at index.js:7)
```

**Comment by sid88in** [comment]
Just tested this with @dabit3 and we don't get an error when using appsync so it might be coming from amplify.

**Comment by manueliglesias** [comment]
Hey @sid88in 

can you make sure  that the versions match
    "aws-appsync": "^1.0.11",
    "aws-appsync-react": "^1.0.5",

in your **yarn.lock**/**package-lock.json**

**Comment by sid88in** [comment]
@manueliglesias yes checked the versions are same as above (I didn't push the yarn to master with new changes). Also, seems like we only get the warning when using amplify with appsync client. 

Are you seeing this warning when you use latest packages of amplify and appsync client?

**Comment by dabit3** [comment]
If it helps, I'm getting the same error using this repo: https://github.com/dabit3/appsync-graphql-cities which may be easier to test because it is only AppSync.

I was able to get the error to go away by adding:
```
options: {
  errorPolicy: 'ignore'
},
```

I found this temporary solution by reading https://github.com/apollographql/react-apollo/issues/604

**Comment by manueliglesias** [comment]
At some point I was getting the warning (everything works, but you get a scary red warning in the console), but then I nuked my node_modules and yarn.lock/package-lock.json, reinstalled dependencies and it went away

Let me know if that works for you to make the warning go away.

Meanwhile, I'll explore having `aws-appsync` as a *peerDependency*  of `aws-appsync-react` instead of a regular dependency

**Comment by sid88in** [comment]
@manueliglesias thanks! yes everything works for sure, but yeah that red warning is scary indeed ;)

**Comment by fgiarritiello** [comment]
I'm getting this error as well. I have tried clearing the nodule_modules and reinstalled the dependencies but no vail. Any help would be appreciated
