### ISSUE TITLE
Real data from AppSync never arrives during optimistic update

### ISSUE THREAD

**Issue by ffxsam** [awslabs/aws-mobile-appsync-sdk-js#59]
In Apollo, when using optimstic UI, `update()` gets called twice, both times with optimistic/fake data. The real data from the network never gets pulled in.

See this StackOverflow question I opened. It has a response from someone which I believe outlines the bug in AppSync:

https://stackoverflow.com/questions/48942175/apollo-update-method-getting-called-twice-both-times-with-optimistic-fake-d

**Comment by tal2** [comment]
Seems to be related to #56.  Possibly a duplicate.

**Comment by tal2** [comment]
@ffxsam I think I just found a workaround. 

The mutation seems to work as expected, if you add this to your mutation configuration.
`context: {AASContext: { doIt: true }},`

At least, the `update` function seems to be called only once with the optimistic result. And then a network error causes the promise to be rejected.

Be careful when you use it, I don't know if there are side effects besides bypassing part of the `OfflineLink`. It is difficult to test with the code from your repository. Partly because the API key is understandably not valid.

If you do try it, please tell me if it works for you and I'll add it to my answer on SO.

**Comment by lolcoolkat** [comment]
Was this ever fixed? I'm dealing with the same thing.. I'm receiving duplicate data in my update function..and not the server data in the 2nd iteration.
