### ISSUE TITLE
Server Side Rendering window is not defined (NextJS)

### ISSUE THREAD

**Issue by ImadBoumzaoued** [awslabs/aws-mobile-appsync-sdk-js#77]
I tried implementing SSR (NextJS) and it throws an error about the window not being defined. Looks like paho-client is the one throwing the error, any solution ?

**Comment by JRobber** [comment]
I'm hitting the same problem in NuxtJS.  I've tracked down what the issue is, but not sure how to fix it.  References : 
https://github.com/awslabs/aws-mobile-appsync-sdk-js/issues/10
https://docs.aws.amazon.com/appsync/latest/devguide/building-a-client-app-javascript.html

Based on those I was able to set a global window object in my config and got passed that error.  The problem is a LOT of build libraries check for window === undefined to know they're in a browser.  Most routing libraries do this, and others.  This makes all SSR rendering engines break because they're trying to access a very incomplete window object. 

AppSync sdk needs to be refactored to abstract out all uses of Window so that config could be passed in it's place.  This will allow other engines to rely on window to know if they're in browser, but give appsync a way to work server side.

**Comment by ImadBoumzaoued** [comment]
@JRobber would you mind sharing your solution ? please

**Comment by apmontgomery** [comment]
Same issue here on Nuxt.  Mocking mocking global.window causes lots of other issues.  This thread: https://github.com/aws/aws-amplify/issues/434 recommends adding the auth-link from aws-appsync to the client link chain in apollo and using that instead of the appsync client.  Has anyone had success with something like that?

**Comment by tgorka** [comment]
#110 should fix the problem. It's probably related to #82 as well

**Comment by rohanray** [comment]
@tgorka node-window-polyfill/register has incomplete window object. I'm using next.js. It breaks on window.location.href with the error href is undefined

**Comment by lolcoolkat** [comment]
@manueliglesias Very much looking forward to the Next.JS (SSR) compatibility with AWS Appsync! Thanks for working on supporting it for those of us who love Next.JS ❤️

**Comment by michaelmerrill** [comment]
@manueliglesias How's this coming along? I noticed that [aws-amplify](https://github.com/aws/aws-amplify/issues/882) is also having issues with its dependency on window. Anything we can do to help?
