### ISSUE TITLE
Third-party GraphQL compatibility

### ISSUE THREAD

**Issue by sebastian-schlecht** [awslabs/aws-mobile-appsync-sdk-js#90]
First of all, thanks for providing this.

Is there a way to use this client to communicate with a third-party graphql endpoint? If now, can I setup a lambda function as a proxy, in order to route requests through to the third-party endpoint?

Any thoughts would be appreciated.

**Comment by manueliglesias** [comment]
Hi @sebastian-schlecht 

This client extends `ApolloClient` **AND** adds AppSync specific functionality (e.g. subscriptions, conflict resolution, complex objects upload, auth, offline support, etc). This means that you can also use it to communicate with third-party endpoints (I am assuming *non AppSync endpoints*?), you just need to provide your own link. Keep in mind that not all the features I mentioned would work with non AppSync endpoints since they require server side support.

Something like this:
```javascript
import AWSAppSyncClient from "aws-appsync";
import { HttpLink } from 'apollo-link-http';

const endpoint = ''; // your graphql endpoint
const client = new AWSAppSyncClient({}, { link: new HttpLink({ uri: endpoint }) });
```
